name: Release obsidian plugin

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - '*' # Push events to matching any tag format, i.e. 1.0, 20.15.10

env:
  PLUGIN_NAME: hotkeysplus-obsidian # Change this to the name of your plugin-id folder

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x' # You might need to adjust this value to your own version
    - name: Create release
      uses: argenos/release-obsidian-plugin-action@v1
      with:
        plugin-id: my-plugin
        css: false # This value is optional, and defaults to true. Only add it if you don't use styles.css